console.log("hello");
console.log("hello");
try{
    console.log(a);
} catch(err) {
    console.log("Caught an error...........");
    console.log(`error is ${err}`);
}
console.log("hello");
console.log("hello");